// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * L​a​n​g​u​a​g​e​ ​C​h​o​o​s​e​r​ ​D​e​m​o
		 */
		title: string
		/**
		 * L​a​n​g​u​a​g​e​ ​D​i​s​p​l​a​y​ ​N​a​m​e​:
		 */
		languageDisplayName: string
		/**
		 * L​a​n​g​u​a​g​e​ ​C​o​d​e​:
		 */
		languageCode: string
		/**
		 * S​c​r​i​p​t​:
		 */
		script: string
		/**
		 * R​e​g​i​o​n​:
		 */
		region: string
		/**
		 * D​i​a​l​e​c​t​:
		 */
		dialect: string
		/**
		 * L​a​n​g​u​a​g​e​ ​T​a​g​:
		 */
		languageTag: string
		/**
		 * M​o​d​i​f​y​ ​L​a​n​g​u​a​g​e​ ​S​e​l​e​c​t​i​o​n
		 */
		modifyLanguageSelection: string
		/**
		 * C​h​o​o​s​e​ ​T​h​e​m​e​:
		 */
		chooseTheme: string
		/**
		 * L​i​g​h​t
		 */
		light: string
		/**
		 * D​a​r​k
		 */
		dark: string
	}
	chooser: {
		/**
		 * C​h​o​o​s​e​ ​L​a​n​g​u​a​g​e
		 */
		chooseLanguage: string
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​n​a​m​e​,​ ​c​o​d​e​,​ ​o​r​ ​c​o​u​n​t​r​y
		 */
		searchPlaceholder: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​s​c​r​i​p​t
		 */
		selectScript: string
		/**
		 * E​d​i​t​ ​L​a​n​g​u​a​g​e​ ​T​a​g
		 */
		editLanguageTag: string
		/**
		 * C​u​s​t​o​m​i​z​e
		 */
		customize: string
		/**
		 * U​n​l​i​s​t​e​d​ ​L​a​n​g​u​a​g​e
		 */
		unlistedLanguage: string
		/**
		 * D​i​s​p​l​a​y​ ​t​h​i​s​ ​l​a​n​g​u​a​g​e​ ​t​h​i​s​ ​w​a​y
		 */
		displayThisLanguageThisWay: string
		/**
		 * O​k
		 */
		ok: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * I​f​ ​t​h​i​s​ ​u​s​e​r​ ​i​n​t​e​r​f​a​c​e​ ​i​s​ ​n​o​t​ ​o​f​f​e​r​i​n​g​ ​y​o​u​ ​a​ ​l​a​n​g​u​a​g​e​ ​t​a​g​ ​t​h​a​t​ ​y​o​u​ ​k​n​o​w​ ​i​s​ ​v​a​l​i​d​ ​I​S​O​ ​6​3​9​ ​c​o​d​e​,​ ​y​o​u​ ​c​a​n​ ​e​n​t​e​r​ ​i​t​ ​h​e​r​e​:
		 */
		customLanguageTagPrompt: string
		/**
		 * T​h​i​s​ ​i​s​ ​n​o​t​ ​i​n​ ​a​ ​v​a​l​i​d​ ​I​E​T​F​ ​B​C​P​ ​4​7​ ​f​o​r​m​a​t​:​ ​{​t​a​g​}
		 * @param {unknown} tag
		 */
		invalidBcp47Format: RequiredParams<'tag'>
	}
	modal: {
		/**
		 * C​u​s​t​o​m​ ​L​a​n​g​u​a​g​e​ ​T​a​g
		 */
		customLanguageTag: string
		/**
		 * U​n​l​i​s​t​e​d​ ​L​a​n​g​u​a​g​e​ ​T​a​g
		 */
		unlistedLanguageTag: string
		/**
		 * E​n​t​e​r​ ​C​u​s​t​o​m​ ​T​a​g
		 */
		enterCustomTag: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Language Chooser Demo
		 */
		title: () => LocalizedString
		/**
		 * Language Display Name:
		 */
		languageDisplayName: () => LocalizedString
		/**
		 * Language Code:
		 */
		languageCode: () => LocalizedString
		/**
		 * Script:
		 */
		script: () => LocalizedString
		/**
		 * Region:
		 */
		region: () => LocalizedString
		/**
		 * Dialect:
		 */
		dialect: () => LocalizedString
		/**
		 * Language Tag:
		 */
		languageTag: () => LocalizedString
		/**
		 * Modify Language Selection
		 */
		modifyLanguageSelection: () => LocalizedString
		/**
		 * Choose Theme:
		 */
		chooseTheme: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
	}
	chooser: {
		/**
		 * Choose Language
		 */
		chooseLanguage: () => LocalizedString
		/**
		 * Search by name, code, or country
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Select a script
		 */
		selectScript: () => LocalizedString
		/**
		 * Edit Language Tag
		 */
		editLanguageTag: () => LocalizedString
		/**
		 * Customize
		 */
		customize: () => LocalizedString
		/**
		 * Unlisted Language
		 */
		unlistedLanguage: () => LocalizedString
		/**
		 * Display this language this way
		 */
		displayThisLanguageThisWay: () => LocalizedString
		/**
		 * Ok
		 */
		ok: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * If this user interface is not offering you a language tag that you know is valid ISO 639 code, you can enter it here:
		 */
		customLanguageTagPrompt: () => LocalizedString
		/**
		 * This is not in a valid IETF BCP 47 format: {tag}
		 */
		invalidBcp47Format: (arg: { tag: unknown }) => LocalizedString
	}
	modal: {
		/**
		 * Custom Language Tag
		 */
		customLanguageTag: () => LocalizedString
		/**
		 * Unlisted Language Tag
		 */
		unlistedLanguageTag: () => LocalizedString
		/**
		 * Enter Custom Tag
		 */
		enterCustomTag: () => LocalizedString
	}
}

export type Formatters = {}
